version: "3"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_obsidian_rag
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_db:/qdrant/storage       # ← RocksDB 永続化
    environment:
      QDRANT__SERVICE__TELEMETRY_DISABLED: "true"
    restart: unless-stopped
